name: Pipline CI/CD build
on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'

jobs:
  check_syntaxe:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.12]

    steps:
      - uses: actions/checkout@v2
      - name: Set up python
        uses: actions/setup-python@v2
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8
          pip install -r requirements.txt

      - name: Check code lint with flake8
        run: |
          flake8 . --exit-zero

  test:
    runs-on: ubuntu-latest
    needs: check_syntaxe
    services:
      postgres:
        image: postgres:15.8
        env:
          POSTGRES_USER: task
          POSTGRES_PASSWORD: task
          POSTGRES_DB: task_test
        ports:
          - 5459:5432
    steps:
      - uses: actions/checkout@v2
      - name: Set up python
        uses: actions/setup-python@v2
        with:
          python-version: '3.12'
      - name: Install dependencies
        run: make install_dev
      - name: Run tests
        run: make test
